

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';


/* PRODUCT */
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_ERROR = 'PRODUCT_ADD_ERROR';
export const ALL_PRODUCT = 'ALL_PRODUCT';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_ERROR = 'ALL_PRODUCT_ERROR';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const  SELECTED_PRODUCT_SUCCESS = ' SELECTED_PRODUCT_SUCCESS';
export const  SELECTED_PRODUCT_ERROR = ' SELECTED_PRODUCT_ERROR';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_ERROR = 'PRODUCT_UPDATE_ERROR';
export const ALL_SELLERS = 'ALL_SELLERS';
export const ALL_SELLERS_SUCCESS = 'ALL_SELLERS_SUCCESS';
export const ALL_SELLERS_ERROR = 'ALL_SELLERS_ERROR';


/* PROFILE */
export const PROFILE = 'PROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';







export * from './auth/actions';

